/* eslint-disable */
// This file is automatically generated by GraphQL Code Generator.

import { gql } from 'apollo-angular';
import { Injectable } from '@angular/core';
import * as Apollo from 'apollo-angular';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends Record<string, unknown>> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends Record<string, unknown>, K extends keyof T> = Partial<Record<K, never>>;
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export interface Scalars {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  DateTime: { input: string; output: string; }
  Upload: { input: File | Blob; output: File | Blob; }
}

export interface BulkDeleteResponse {
  __typename?: 'BulkDeleteResponse';
  errors?: Maybe<Error[]>;
  failedIds: Scalars['String']['output'][];
  success: Scalars['Boolean']['output'];
  successIds: Scalars['String']['output'][];
}

export interface Error {
  __typename?: 'Error';
  code?: Maybe<Scalars['String']['output']>;
  field?: Maybe<Scalars['String']['output']>;
  message: Scalars['String']['output'];
}

export interface Genre {
  __typename?: 'Genre';
  createdAt: Scalars['String']['output'];
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  updatedAt: Scalars['String']['output'];
}

export interface Mutation {
  __typename?: 'Mutation';
  createTrack: Track;
  deleteTrack: Scalars['Boolean']['output'];
  deleteTrackFile: Track;
  deleteTracks: BulkDeleteResponse;
  updateTrack: Track;
  uploadTrackFile: Track;
}


export interface MutationCreateTrackArgs {
  input: TrackCreateInput;
}


export interface MutationDeleteTrackArgs {
  id: Scalars['String']['input'];
}


export interface MutationDeleteTrackFileArgs {
  id: Scalars['String']['input'];
}


export interface MutationDeleteTracksArgs {
  ids: Scalars['String']['input'][];
}


export interface MutationUpdateTrackArgs {
  id: Scalars['String']['input'];
  input: TrackUpdateInput;
}


export interface MutationUploadTrackFileArgs {
  file: Scalars['Upload']['input'];
  id: Scalars['String']['input'];
}

export interface PageInfo {
  __typename?: 'PageInfo';
  limit: Scalars['Int']['output'];
  page: Scalars['Int']['output'];
  total: Scalars['Int']['output'];
  totalPages: Scalars['Int']['output'];
}

export interface PaginationInput {
  limit?: InputMaybe<Scalars['Int']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
}

export interface Query {
  __typename?: 'Query';
  genre?: Maybe<Genre>;
  genreBySlug?: Maybe<Genre>;
  genres: Genre[];
  track?: Maybe<Track>;
  trackBySlug?: Maybe<Track>;
  tracks: TracksConnection;
}


export interface QueryGenreArgs {
  id: Scalars['String']['input'];
}


export interface QueryGenreBySlugArgs {
  slug: Scalars['String']['input'];
}


export interface QueryTrackArgs {
  id: Scalars['String']['input'];
}


export interface QueryTrackBySlugArgs {
  slug: Scalars['String']['input'];
}


export interface QueryTracksArgs {
  input?: InputMaybe<TracksInput>;
}

export enum SortOrder {
  Asc = 'ASC',
  Desc = 'DESC'
}

export interface Track {
  __typename?: 'Track';
  album?: Maybe<Scalars['String']['output']>;
  artist: Scalars['String']['output'];
  audioFile?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['String']['output'];
  genres: Scalars['String']['output'][];
  id: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['String']['output'];
}

export interface TrackCreateInput {
  album?: InputMaybe<Scalars['String']['input']>;
  artist: Scalars['String']['input'];
  coverImage?: InputMaybe<Scalars['String']['input']>;
  genres: Scalars['String']['input'][];
  title: Scalars['String']['input'];
}

export enum TrackSortField {
  Album = 'ALBUM',
  Artist = 'ARTIST',
  CreatedAt = 'CREATED_AT',
  Title = 'TITLE',
  UpdatedAt = 'UPDATED_AT'
}

export interface TrackUpdateInput {
  album?: InputMaybe<Scalars['String']['input']>;
  artist?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  genres?: InputMaybe<Scalars['String']['input'][]>;
  title?: InputMaybe<Scalars['String']['input']>;
}

export interface TracksConnection {
  __typename?: 'TracksConnection';
  data: Track[];
  pageInfo: PageInfo;
}

export interface TracksFilterInput {
  artist?: InputMaybe<Scalars['String']['input']>;
  genre?: InputMaybe<Scalars['String']['input']>;
  search?: InputMaybe<Scalars['String']['input']>;
}

export interface TracksInput {
  filter?: InputMaybe<TracksFilterInput>;
  pagination?: InputMaybe<PaginationInput>;
  sort?: InputMaybe<TracksSortInput>;
}

export interface TracksSortInput {
  field?: InputMaybe<TrackSortField>;
  order?: InputMaybe<SortOrder>;
}

export type BulkDeleteTracksMutationVariables = Exact<{
  ids: Scalars['String']['input'][] | Scalars['String']['input'];
}>;


export interface BulkDeleteTracksMutation { __typename?: 'Mutation', deleteTracks: { __typename?: 'BulkDeleteResponse', success: boolean, successIds: string[], failedIds: string[], errors?: { __typename?: 'Error', message: string, code?: string | null, field?: string | null }[] | null } }

export type CreateTrackMutationVariables = Exact<{
  input: TrackCreateInput;
}>;


export interface CreateTrackMutation { __typename?: 'Mutation', createTrack: { __typename?: 'Track', id: string, title: string, artist: string, album?: string | null, genres: string[], slug: string, coverImage?: string | null, audioFile?: string | null, createdAt: string, updatedAt: string } }

export type DeleteTrackFileMutationVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export interface DeleteTrackFileMutation { __typename?: 'Mutation', deleteTrackFile: { __typename?: 'Track', id: string, title: string, artist: string, album?: string | null, genres: string[], slug: string, coverImage?: string | null, audioFile?: string | null, createdAt: string, updatedAt: string } }

export type DeleteTrackMutationVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export interface DeleteTrackMutation { __typename?: 'Mutation', deleteTrack: boolean }

export type DeleteTracksMutationVariables = Exact<{
  ids: Scalars['String']['input'][] | Scalars['String']['input'];
}>;


export interface DeleteTracksMutation { __typename?: 'Mutation', deleteTracks: { __typename?: 'BulkDeleteResponse', success: boolean, successIds: string[], failedIds: string[], errors?: { __typename?: 'Error', message: string, code?: string | null, field?: string | null }[] | null } }

export type UpdateTrackMutationVariables = Exact<{
  id: Scalars['String']['input'];
  input: TrackUpdateInput;
}>;


export interface UpdateTrackMutation { __typename?: 'Mutation', updateTrack: { __typename?: 'Track', id: string, title: string, artist: string, album?: string | null, genres: string[], slug: string, coverImage?: string | null, audioFile?: string | null, createdAt: string, updatedAt: string } }

export type UploadTrackFileMutationVariables = Exact<{
  id: Scalars['String']['input'];
  file: Scalars['Upload']['input'];
}>;


export interface UploadTrackFileMutation { __typename?: 'Mutation', uploadTrackFile: { __typename?: 'Track', id: string, title: string, artist: string, album?: string | null, genres: string[], slug: string, coverImage?: string | null, audioFile?: string | null, createdAt: string, updatedAt: string } }

export type GetGenresQueryVariables = Exact<Record<string, never>>;


export interface GetGenresQuery { __typename?: 'Query', genres: { __typename?: 'Genre', id: string, name: string, slug: string }[] }

export type GetTracksQueryVariables = Exact<{
  input?: InputMaybe<TracksInput>;
}>;


export interface GetTracksQuery { __typename?: 'Query', tracks: { __typename?: 'TracksConnection', data: { __typename?: 'Track', id: string, title: string, artist: string, album?: string | null, genres: string[], slug: string, coverImage?: string | null, audioFile?: string | null, createdAt: string, updatedAt: string }[], pageInfo: { __typename?: 'PageInfo', total: number, page: number, limit: number, totalPages: number } } }

export const BulkDeleteTracksDocument = gql`
    mutation BulkDeleteTracks($ids: [String!]!) {
  deleteTracks(ids: $ids) {
    success
    successIds
    failedIds
    errors {
      message
      code
      field
    }
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class BulkDeleteTracksGQL extends Apollo.Mutation<BulkDeleteTracksMutation, BulkDeleteTracksMutationVariables> {
    override document = BulkDeleteTracksDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const CreateTrackDocument = gql`
    mutation CreateTrack($input: TrackCreateInput!) {
  createTrack(input: $input) {
    id
    title
    artist
    album
    genres
    slug
    coverImage
    audioFile
    createdAt
    updatedAt
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class CreateTrackGQL extends Apollo.Mutation<CreateTrackMutation, CreateTrackMutationVariables> {
    override document = CreateTrackDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const DeleteTrackFileDocument = gql`
    mutation DeleteTrackFile($id: String!) {
  deleteTrackFile(id: $id) {
    id
    title
    artist
    album
    genres
    slug
    coverImage
    audioFile
    createdAt
    updatedAt
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class DeleteTrackFileGQL extends Apollo.Mutation<DeleteTrackFileMutation, DeleteTrackFileMutationVariables> {
    override document = DeleteTrackFileDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const DeleteTrackDocument = gql`
    mutation DeleteTrack($id: String!) {
  deleteTrack(id: $id)
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class DeleteTrackGQL extends Apollo.Mutation<DeleteTrackMutation, DeleteTrackMutationVariables> {
    override document = DeleteTrackDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const DeleteTracksDocument = gql`
    mutation DeleteTracks($ids: [String!]!) {
  deleteTracks(ids: $ids) {
    success
    successIds
    failedIds
    errors {
      message
      code
      field
    }
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class DeleteTracksGQL extends Apollo.Mutation<DeleteTracksMutation, DeleteTracksMutationVariables> {
    override document = DeleteTracksDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const UpdateTrackDocument = gql`
    mutation UpdateTrack($id: String!, $input: TrackUpdateInput!) {
  updateTrack(id: $id, input: $input) {
    id
    title
    artist
    album
    genres
    slug
    coverImage
    audioFile
    createdAt
    updatedAt
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class UpdateTrackGQL extends Apollo.Mutation<UpdateTrackMutation, UpdateTrackMutationVariables> {
    override document = UpdateTrackDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const UploadTrackFileDocument = gql`
    mutation UploadTrackFile($id: String!, $file: Upload!) {
  uploadTrackFile(id: $id, file: $file) {
    id
    title
    artist
    album
    genres
    slug
    coverImage
    audioFile
    createdAt
    updatedAt
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class UploadTrackFileGQL extends Apollo.Mutation<UploadTrackFileMutation, UploadTrackFileMutationVariables> {
    override document = UploadTrackFileDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const GetGenresDocument = gql`
    query GetGenres {
  genres {
    id
    name
    slug
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class GetGenresGQL extends Apollo.Query<GetGenresQuery, GetGenresQueryVariables> {
    override document = GetGenresDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
export const GetTracksDocument = gql`
    query GetTracks($input: TracksInput) {
  tracks(input: $input) {
    data {
      id
      title
      artist
      album
      genres
      slug
      coverImage
      audioFile
      createdAt
      updatedAt
    }
    pageInfo {
      total
      page
      limit
      totalPages
    }
  }
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class GetTracksGQL extends Apollo.Query<GetTracksQuery, GetTracksQueryVariables> {
    override document = GetTracksDocument;

    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
